/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -w -fpermissive  -I/usr/share/nim -o /home/sangho/Documents/Euiler/Euler.nim/nimcache/E1.o /home/sangho/Documents/Euiler/Euler.nim/nimcache/E1.cpp */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
struct NimStringDesc;
struct TGenericSeq;
struct tySequence_qwqHTkRvwhrRyENtudHQ7g;
struct TNimType;
struct TNimNode;
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA;
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NI x, void* ClE_0);
void* ClE_0;
} tyProc_XP9aH6ptVQfqrEDkUiLoDvA;
typedef N_CLOSURE_PTR(NIM_BOOL, TM_k3rWAHgMLQPHWpejpW26fg_2) (NI x);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(NIM_BOOL, TM_k3rWAHgMLQPHWpejpW26fg_11) (NI x, void* ClE_0);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ : public tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg : public tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g : TGenericSeq {
  NI data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, sum_gbIPXmHbH9cB6gW9ceVVFvbQ)(NI* x, NI xLen_0);
static N_INLINE(tySequence_qwqHTkRvwhrRyENtudHQ7g*, filter_yVHp5J9aELxVOqBGzJbddRgE1)(NI* s, NI sLen_0, tyProc_XP9aH6ptVQfqrEDkUiLoDvA pred);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_k3rWAHgMLQPHWpejpW26fg_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQE1)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5QE1)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w& s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__beWGDtrJmL9cGYwMndr3iGA)(NI x);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, E1DatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NI i_dEeaK41Jvy89a9ak54f9c8l4g;
tySequence_qwqHTkRvwhrRyENtudHQ7g* result_xNy9aJS2UTzKXXNNY5YIBEg;
extern TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NI x_RLi0kMuJRtDWAff9aY7MWXQ;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
{		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tySequence_qwqHTkRvwhrRyENtudHQ7g*, filter_yVHp5J9aELxVOqBGzJbddRgE1)(NI* s, NI sLen_0, tyProc_XP9aH6ptVQfqrEDkUiLoDvA pred) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	nimfr_("filter", "sequtils.nim");
	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	nimln_(728, "system.nim");
	result = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI) 0));
	{
		NI i;
		NI colontmp_;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(309, "sequtils.nim");
		colontmp_ = sLen_0;
		nimln_(3519, "system.nim");
		NI i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_k3rWAHgMLQPHWpejpW26fg_3;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				nimln_(310, "sequtils.nim");
				{
					NIM_BOOL T6_;
					NI T9_;
					if ((NU)(i) >= (NU)(sLen_0)) raiseIndexError();
					T6_ = (NIM_BOOL)0;
					T6_ = pred.ClE_0? pred.ClP_0(s[i], pred.ClE_0):((TM_k3rWAHgMLQPHWpejpW26fg_2)(pred.ClP_0))(s[i]);
					if (!T6_) goto LA7_;
{					nimln_(311, "sequtils.nim");
					if ((NU)(i) >= (NU)(sLen_0)) raiseIndexError();
					result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) incrSeqV2(result, sizeof(NI));
					T9_ = result->len++;
					result->data[T9_] = s[i];
}				}
				LA7_: ;
				nimln_(3522, "system.nim");
				TM_k3rWAHgMLQPHWpejpW26fg_3 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_k3rWAHgMLQPHWpejpW26fg_3);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_k3rWAHgMLQPHWpejpW26fg_4)(void) {
	nimGCvisit((void*)result_xNy9aJS2UTzKXXNNY5YIBEg, 0);
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQE1)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NI result;
	NI TM_k3rWAHgMLQPHWpejpW26fg_5;
	NI TM_k3rWAHgMLQPHWpejpW26fg_6;
	nimfr_("len", "system.nim");
	result = (NI)0;
	nimln_(2181, "system.nim");
	TM_k3rWAHgMLQPHWpejpW26fg_5 = subInt(x.b, x.a);
	TM_k3rWAHgMLQPHWpejpW26fg_6 = addInt((NI)(TM_k3rWAHgMLQPHWpejpW26fg_5), ((NI) 1));
	result = ((((NI) 0) >= (NI)(TM_k3rWAHgMLQPHWpejpW26fg_6)) ? ((NI) 0) : (NI)(TM_k3rWAHgMLQPHWpejpW26fg_6));
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5QE1)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = i;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw(gch_IcYaEuuWivYAS86vFMTS3Q.zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
{		nimln_(272, "gc.nim");
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
}	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
{		nimln_(275, "gc.nim");
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
{			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
}		}
		LA11_: ;
}	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__beWGDtrJmL9cGYwMndr3iGA)(NI x) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI TM_k3rWAHgMLQPHWpejpW26fg_9;
	NI TM_k3rWAHgMLQPHWpejpW26fg_10;
	nimfr_(":anonymous", "E1.nim");
	result = (NIM_BOOL)0;
	nimln_(3, "E1.nim");
	T1_ = (NIM_BOOL)0;
	TM_k3rWAHgMLQPHWpejpW26fg_9 = modInt(x, ((NI) 3));
	T1_ = ((NI)(TM_k3rWAHgMLQPHWpejpW26fg_9) == ((NI) 0));
	if (T1_) goto LA2_;
	TM_k3rWAHgMLQPHWpejpW26fg_10 = modInt(x, ((NI) 5));
	T1_ = ((NI)(TM_k3rWAHgMLQPHWpejpW26fg_10) == ((NI) 0));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_futureDatInit000();
	stdlib_mathDatInit000();
	stdlib_sequtilsDatInit000();
	E1DatInit000();
	stdlib_macrosInit000();
	stdlib_futureInit000();
	stdlib_mathInit000();
	stdlib_sequtilsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NI T2_;
	tyProc_XP9aH6ptVQfqrEDkUiLoDvA T6_;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* T7_;
	NI T8_;
	nimfr_("E1", "E1.nim");
nimRegisterGlobalMarker(TM_k3rWAHgMLQPHWpejpW26fg_4);
	nimln_(3, "E1.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	nimln_(500, "sequtils.nim");
	i_dEeaK41Jvy89a9ak54f9c8l4g = ((NI) 0);
	nimln_(501, "sequtils.nim");
	nimln_(3, "E1.nim");
	T2_ = (NI)0;
	T2_ = len_dieebyw8huA9adTlIwdsH9bQE1(dotdot__vDQySKWzgnxQdUarow6k5QE1(((NI) 1), ((NI) 999)));
	asgnRefNoCycle((void**) (&result_xNy9aJS2UTzKXXNNY5YIBEg), newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange(T2_, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	{
		nimln_(2045, "system.nim");
		NI res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_k3rWAHgMLQPHWpejpW26fg_7;
				NI TM_k3rWAHgMLQPHWpejpW26fg_8;
				if (!(res <= ((NI) 999))) goto LA5;
				nimln_(2047, "system.nim");
				x_RLi0kMuJRtDWAff9aY7MWXQ = res;
				if ((NU)(i_dEeaK41Jvy89a9ak54f9c8l4g) >= (NU)(result_xNy9aJS2UTzKXXNNY5YIBEg->len)) raiseIndexError();
				nimln_(503, "sequtils.nim");
				result_xNy9aJS2UTzKXXNNY5YIBEg->data[i_dEeaK41Jvy89a9ak54f9c8l4g] = x_RLi0kMuJRtDWAff9aY7MWXQ;
				nimln_(504, "sequtils.nim");
				TM_k3rWAHgMLQPHWpejpW26fg_7 = addInt(i_dEeaK41Jvy89a9ak54f9c8l4g, ((NI) 1));
				i_dEeaK41Jvy89a9ak54f9c8l4g = (NI)(TM_k3rWAHgMLQPHWpejpW26fg_7);
				nimln_(2048, "system.nim");
				TM_k3rWAHgMLQPHWpejpW26fg_8 = addInt(res, ((NI) 1));
				res = (NI)(TM_k3rWAHgMLQPHWpejpW26fg_8);
			} LA5: ;
		}
	}
	memset((void*)(&T6_), 0, sizeof(T6_));
	T6_.ClP_0 = ((TM_k3rWAHgMLQPHWpejpW26fg_11) (colonanonymous__beWGDtrJmL9cGYwMndr3iGA)); T6_.ClE_0 = NIM_NIL;
	T7_ = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	T7_ = filter_yVHp5J9aELxVOqBGzJbddRgE1(result_xNy9aJS2UTzKXXNNY5YIBEg->data, result_xNy9aJS2UTzKXXNNY5YIBEg->len, T6_);
	T8_ = (NI)0;
	T8_ = sum_gbIPXmHbH9cB6gW9ceVVFvbQ(T7_->data, T7_->len);
	T1_[0] = nimIntToStr(T8_);
	echoBinSafe(T1_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, E1DatInit000)(void) {
}

