/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -I/usr/share/nim -o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E2.o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NI, fibo_uhPOvdB6zNwInwYmQ4r9cyQ)(NI l);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, main_Y9apEWKs4IZ5CMPUeJ0tu4w)(void);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, E2DatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, fibo_uhPOvdB6zNwInwYmQ4r9cyQ)(NI l) {
	NI result;
	NI a;
	NI b;
	NI c;
	nimfr_("fibo", "E2.nim");
{	result = (NI)0;
	nimln_(4, "E2.nim");
	a = ((NI) 1);
	b = ((NI) 1);
	nimln_(5, "E2.nim");
	c = a;
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_8a9cd9biGrnPDLfpFQytbaHA_2;
				NI TM_8a9cd9biGrnPDLfpFQytbaHA_3;
				if (!(res <= l)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(7, "E2.nim");
				c = a;
				nimln_(8, "E2.nim");
				a = b;
				nimln_(9, "E2.nim");
				TM_8a9cd9biGrnPDLfpFQytbaHA_2 = addInt(c, b);
				b = (NI)(TM_8a9cd9biGrnPDLfpFQytbaHA_2);
				nimln_(2048, "system.nim");
				TM_8a9cd9biGrnPDLfpFQytbaHA_3 = addInt(res, ((NI) 1));
				res = (NI)(TM_8a9cd9biGrnPDLfpFQytbaHA_3);
			} LA3: ;
		}
	}
	nimln_(10, "E2.nim");
	result = a;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_Y9apEWKs4IZ5CMPUeJ0tu4w)(void) {
	NI s;
	NI l;
	tyArray_nHXaesL0DJZHyVS07ARPRA T10_;
	nimfr_("main", "E2.nim");
	nimln_(13, "E2.nim");
	s = ((NI) 0);
	nimln_(14, "E2.nim");
	l = ((NI) 1);
	{
		nimln_(15, "E2.nim");
		while (1) {
			NI T3_;
			NI TM_8a9cd9biGrnPDLfpFQytbaHA_6;
			T3_ = (NI)0;
			T3_ = fibo_uhPOvdB6zNwInwYmQ4r9cyQ(l);
			if (!(T3_ < ((NI) 4000000))) goto LA2;
			nimln_(16, "E2.nim");
			{
				NI T6_;
				NI TM_8a9cd9biGrnPDLfpFQytbaHA_4;
				NI T9_;
				NI TM_8a9cd9biGrnPDLfpFQytbaHA_5;
				T6_ = (NI)0;
				T6_ = fibo_uhPOvdB6zNwInwYmQ4r9cyQ(l);
				TM_8a9cd9biGrnPDLfpFQytbaHA_4 = modInt(T6_, ((NI) 2));
				if (!((NI)(TM_8a9cd9biGrnPDLfpFQytbaHA_4) == ((NI) 0))) goto LA7_;
				nimln_(17, "E2.nim");
				T9_ = (NI)0;
				T9_ = fibo_uhPOvdB6zNwInwYmQ4r9cyQ(l);
				TM_8a9cd9biGrnPDLfpFQytbaHA_5 = addInt(s, T9_);
				s = (NI)(TM_8a9cd9biGrnPDLfpFQytbaHA_5);
			}
			LA7_: ;
			nimln_(18, "E2.nim");
			TM_8a9cd9biGrnPDLfpFQytbaHA_6 = addInt(l, ((NI) 1));
			l = (NI)(TM_8a9cd9biGrnPDLfpFQytbaHA_6);
		} LA2: ;
	}
	nimln_(19, "E2.nim");
	memset((void*)T10_, 0, sizeof(T10_));
	T10_[0] = nimIntToStr(s);
	echoBinSafe(T10_, 1);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	E2DatInit000();
	stdlib_mathInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("E2", "E2.nim");
	nimln_(21, "E2.nim");
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(22, "E2.nim");
		main_Y9apEWKs4IZ5CMPUeJ0tu4w();
	}
	LA3_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, E2DatInit000)(void) {
}

