/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -I/usr/share/nim -o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E4.o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E4.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, palindrome_v1TeqyXHHLJ3hlZqp1Io8A)(NI n);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_CHAR, X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgsystem)(NimStringDesc* s, NI i);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, main_mHvT9bfIWg79c3Pel3ftURHA)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, E4DatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_CHAR, X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgsystem)(NimStringDesc* s, NI i) {
	NIM_CHAR result;
	NI TM_IiU00JVNosxA4l2Dk7oeiA_2;
	nimfr_("[]", "system.nim");
	result = (NIM_CHAR)0;
	nimln_(3626, "system.nim");
	TM_IiU00JVNosxA4l2Dk7oeiA_2 = subInt((s ? s->Sup.len : 0), i);
	if ((NU)((NI)(TM_IiU00JVNosxA4l2Dk7oeiA_2)) > (NU)(s->Sup.len)) raiseIndexError();
	result = s->data[(NI)(TM_IiU00JVNosxA4l2Dk7oeiA_2)];
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, palindrome_v1TeqyXHHLJ3hlZqp1Io8A)(NI n) {
	NIM_BOOL result;
	NimStringDesc* origin;
	NimStringDesc* reversed;
	nimfr_("palindrome", "E4.nim");
{	result = (NIM_BOOL)0;
	nimln_(4, "E4.nim");
	origin = nimIntToStr(n);
	nimln_(5, "E4.nim");
	reversed = nimIntToStr(n);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(6, "E4.nim");
		colontmp_ = (origin ? (origin->Sup.len-1) : -1);
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_IiU00JVNosxA4l2Dk7oeiA_3;
				NI TM_IiU00JVNosxA4l2Dk7oeiA_4;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				if ((NU)(i) > (NU)(reversed->Sup.len)) raiseIndexError();
				nimln_(7, "E4.nim");
				TM_IiU00JVNosxA4l2Dk7oeiA_3 = addInt(i, ((NI) 1));
				reversed->data[i] = X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgsystem(origin, (NI)(TM_IiU00JVNosxA4l2Dk7oeiA_3));
				nimln_(2048, "system.nim");
				TM_IiU00JVNosxA4l2Dk7oeiA_4 = addInt(res, ((NI) 1));
				res = (NI)(TM_IiU00JVNosxA4l2Dk7oeiA_4);
			} LA3: ;
		}
	}
	nimln_(8, "E4.nim");
	result = eqStrings(reversed, origin);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_mHvT9bfIWg79c3Pel3ftURHA)(void) {
	NI max_num;
	tyArray_nHXaesL0DJZHyVS07ARPRA T13_;
	nimfr_("main", "E4.nim");
	nimln_(11, "E4.nim");
	max_num = ((NI) 0);
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 100);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_IiU00JVNosxA4l2Dk7oeiA_9;
				if (!(res <= ((NI) 999))) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				{
					NI j;
					NI res_2;
					j = (NI)0;
					nimln_(2045, "system.nim");
					res_2 = i;
					{
						nimln_(2046, "system.nim");
						while (1) {
							NI TM_IiU00JVNosxA4l2Dk7oeiA_8;
							if (!(res_2 <= ((NI) 999))) goto LA6;
							nimln_(2047, "system.nim");
							j = res_2;
							nimln_(14, "E4.nim");
							{
								NIM_BOOL T9_;
								NI TM_IiU00JVNosxA4l2Dk7oeiA_5;
								NI TM_IiU00JVNosxA4l2Dk7oeiA_6;
								NI TM_IiU00JVNosxA4l2Dk7oeiA_7;
								T9_ = (NIM_BOOL)0;
								TM_IiU00JVNosxA4l2Dk7oeiA_5 = mulInt(i, j);
								T9_ = palindrome_v1TeqyXHHLJ3hlZqp1Io8A((NI)(TM_IiU00JVNosxA4l2Dk7oeiA_5));
								if (!(T9_)) goto LA10_;
								TM_IiU00JVNosxA4l2Dk7oeiA_6 = mulInt(i, j);
								T9_ = (max_num < (NI)(TM_IiU00JVNosxA4l2Dk7oeiA_6));
								LA10_: ;
								if (!T9_) goto LA11_;
								nimln_(15, "E4.nim");
								TM_IiU00JVNosxA4l2Dk7oeiA_7 = mulInt(i, j);
								max_num = (NI)(TM_IiU00JVNosxA4l2Dk7oeiA_7);
							}
							LA11_: ;
							nimln_(2048, "system.nim");
							TM_IiU00JVNosxA4l2Dk7oeiA_8 = addInt(res_2, ((NI) 1));
							res_2 = (NI)(TM_IiU00JVNosxA4l2Dk7oeiA_8);
						} LA6: ;
					}
				}
				TM_IiU00JVNosxA4l2Dk7oeiA_9 = addInt(res, ((NI) 1));
				res = (NI)(TM_IiU00JVNosxA4l2Dk7oeiA_9);
			} LA3: ;
		}
	}
	nimln_(17, "E4.nim");
	memset((void*)T13_, 0, sizeof(T13_));
	T13_[0] = nimIntToStr(max_num);
	echoBinSafe(T13_, 1);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	E4DatInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("E4", "E4.nim");
	nimln_(19, "E4.nim");
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(20, "E4.nim");
		main_mHvT9bfIWg79c3Pel3ftURHA();
	}
	LA3_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, E4DatInit000)(void) {
}

