/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -w -fpermissive  -I/usr/share/nim -o /home/sangho/Documents/Euiler/NIM/nim.Euler/nimcache/E5.o /home/sangho/Documents/Euiler/NIM/nim.Euler/nimcache/E5.cpp */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
struct NimStringDesc;
struct TGenericSeq;
struct tySequence_qwqHTkRvwhrRyENtudHQ7g;
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g : TGenericSeq {
  NI data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, gcd_NyIYzlvRlaYMXjC9bFXqILg)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, lcm_NyIYzlvRlaYMXjC9bFXqILg_2)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, main_qXw3Fibbv9bkSwxKTVxtwXQ)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQE5)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5QE5)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, E5DatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_v5STcsFPbORM5eGVfZSgyw_9, "\0120 < len(s123306) Can\'t fold empty sequences", 44);

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
{		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, gcd_NyIYzlvRlaYMXjC9bFXqILg)(NI a, NI b) {
	NI result;
	nimfr_("gcd", "E5.nim");
{	result = (NI)0;
	nimln_(4, "E5.nim");
	{
		if (!(b == ((NI) 0))) goto LA3_;
{		nimln_(5, "E5.nim");
		result = a;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_v5STcsFPbORM5eGVfZSgyw_2;
		nimln_(7, "E5.nim");
		TM_v5STcsFPbORM5eGVfZSgyw_2 = modInt(a, b);
		result = gcd_NyIYzlvRlaYMXjC9bFXqILg(b, (NI)(TM_v5STcsFPbORM5eGVfZSgyw_2));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
{		raiseOverflow();
}	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, lcm_NyIYzlvRlaYMXjC9bFXqILg_2)(NI a, NI b) {
	NI result;
	NI TM_v5STcsFPbORM5eGVfZSgyw_3;
	NI T1_;
	NI TM_v5STcsFPbORM5eGVfZSgyw_4;
	nimfr_("lcm", "E5.nim");
	result = (NI)0;
	nimln_(10, "E5.nim");
	TM_v5STcsFPbORM5eGVfZSgyw_3 = mulInt(a, b);
	T1_ = (NI)0;
	T1_ = gcd_NyIYzlvRlaYMXjC9bFXqILg(a, b);
	TM_v5STcsFPbORM5eGVfZSgyw_4 = divInt((NI)(TM_v5STcsFPbORM5eGVfZSgyw_3), T1_);
	result = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_4);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQE5)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NI result;
	NI TM_v5STcsFPbORM5eGVfZSgyw_5;
	NI TM_v5STcsFPbORM5eGVfZSgyw_6;
	nimfr_("len", "system.nim");
	result = (NI)0;
	nimln_(2181, "system.nim");
	TM_v5STcsFPbORM5eGVfZSgyw_5 = subInt(x.b, x.a);
	TM_v5STcsFPbORM5eGVfZSgyw_6 = addInt((NI)(TM_v5STcsFPbORM5eGVfZSgyw_5), ((NI) 1));
	result = ((((NI) 0) >= (NI)(TM_v5STcsFPbORM5eGVfZSgyw_6)) ? ((NI) 0) : (NI)(TM_v5STcsFPbORM5eGVfZSgyw_6));
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5QE5)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = i;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_qXw3Fibbv9bkSwxKTVxtwXQ)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* s;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	NI T2_;
	NI result_2;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result_3;
	NI T11_;
	NI T15_;
	NI TM_v5STcsFPbORM5eGVfZSgyw_12;
	nimfr_("main", "E5.nim");
	nimln_(13, "E5.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	nimln_(605, "sequtils.nim");
	nimln_(500, "sequtils.nim");
	NI i = ((NI) 0);
	nimln_(501, "sequtils.nim");
	nimln_(13, "E5.nim");
	T2_ = (NI)0;
	T2_ = len_dieebyw8huA9adTlIwdsH9bQE5(dotdot__vDQySKWzgnxQdUarow6k5QE5(((NI) 1), ((NI) 20)));
	result = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange(T2_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI x;
		x = (NI)0;
		nimln_(2045, "system.nim");
		NI res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_v5STcsFPbORM5eGVfZSgyw_7;
				NI TM_v5STcsFPbORM5eGVfZSgyw_8;
				if (!(res <= ((NI) 20))) goto LA5;
				nimln_(2047, "system.nim");
				x = res;
				if ((NU)(i) >= (NU)(result->len)) raiseIndexError();
				nimln_(503, "sequtils.nim");
				result->data[i] = x;
				nimln_(504, "sequtils.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_7 = addInt(i, ((NI) 1));
				i = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_7);
				nimln_(2048, "system.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_8 = addInt(res, ((NI) 1));
				res = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_8);
			} LA5: ;
		}
	}
	s = result;
	nimln_(606, "sequtils.nim");
	{
		NI T8_;
		T8_ = (s ? s->len : 0);
		if (!!((((NI) 0) < T8_))) goto LA9_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_v5STcsFPbORM5eGVfZSgyw_9));
}	}
	LA9_: ;
	result_2 = (NI)0;
	nimln_(608, "sequtils.nim");
	nimln_(500, "sequtils.nim");
	NI i_2 = ((NI) 0);
	nimln_(501, "sequtils.nim");
	nimln_(13, "E5.nim");
	T11_ = (NI)0;
	T11_ = len_dieebyw8huA9adTlIwdsH9bQE5(dotdot__vDQySKWzgnxQdUarow6k5QE5(((NI) 1), ((NI) 20)));
	result_3 = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange(T11_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI x_2;
		x_2 = (NI)0;
		nimln_(2045, "system.nim");
		NI res_2 = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_v5STcsFPbORM5eGVfZSgyw_10;
				NI TM_v5STcsFPbORM5eGVfZSgyw_11;
				if (!(res_2 <= ((NI) 20))) goto LA14;
				nimln_(2047, "system.nim");
				x_2 = res_2;
				if ((NU)(i_2) >= (NU)(result_3->len)) raiseIndexError();
				nimln_(503, "sequtils.nim");
				result_3->data[i_2] = x_2;
				nimln_(504, "sequtils.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_10 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_10);
				nimln_(2048, "system.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_11 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_11);
			} LA14: ;
		}
	}
	nimln_(608, "sequtils.nim");
	T15_ = (s ? s->len : 0);
	TM_v5STcsFPbORM5eGVfZSgyw_12 = subInt(T15_, ((NI) 1));
	if ((NU)((NI)(TM_v5STcsFPbORM5eGVfZSgyw_12)) >= (NU)(result_3->len)) raiseIndexError();
	result_2 = result_3->data[(NI)(TM_v5STcsFPbORM5eGVfZSgyw_12)];
	{
		NI i_3;
		NI colontmp_;
		NI T17_;
		NI TM_v5STcsFPbORM5eGVfZSgyw_13;
		i_3 = (NI)0;
		colontmp_ = (NI)0;
		nimln_(609, "sequtils.nim");
		T17_ = (s ? s->len : 0);
		TM_v5STcsFPbORM5eGVfZSgyw_13 = subInt(T17_, ((NI) 2));
		colontmp_ = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_13);
		nimln_(2015, "system.nim");
		NI res_3 = colontmp_;
		{
			nimln_(2016, "system.nim");
			while (1) {
				NI TM_v5STcsFPbORM5eGVfZSgyw_14;
				nimln_(609, "sequtils.nim");
				if (!(((NI) 0) <= res_3)) goto LA19;
				nimln_(2017, "system.nim");
				i_3 = res_3;
				nimln_(611, "sequtils.nim");
				if ((NU)(i_3) >= (NU)(s->len)) raiseIndexError();
				NI a = s->data[i_3];
				nimln_(612, "sequtils.nim");
				NI b = result_2;
				nimln_(13, "E5.nim");
				result_2 = lcm_NyIYzlvRlaYMXjC9bFXqILg_2(a, b);
				nimln_(2018, "system.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_14 = subInt(res_3, ((NI) 1));
				res_3 = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_14);
			} LA19: ;
		}
	}
	T1_[0] = nimIntToStr(result_2);
	echoBinSafe(T1_, 1);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_futureDatInit000();
	stdlib_mathDatInit000();
	stdlib_sequtilsDatInit000();
	E5DatInit000();
	stdlib_macrosInit000();
	stdlib_futureInit000();
	stdlib_mathInit000();
	stdlib_sequtilsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("E5", "E5.nim");
	nimln_(15, "E5.nim");
	{
		if (!NIM_TRUE) goto LA3_;
{		nimln_(16, "E5.nim");
		main_qXw3Fibbv9bkSwxKTVxtwXQ();
}	}
	LA3_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, E5DatInit000)(void) {
}

