/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -I/usr/share/nim -o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E5.o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E5.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, gcd_NyIYzlvRlaYMXjC9bFXqILg)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, lcm_NyIYzlvRlaYMXjC9bFXqILg_2)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, lcm2_U9cX9bzGSpzbFx9aiSoGcVS5g)(tySequence_qwqHTkRvwhrRyENtudHQ7g* A);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, main_qXw3Fibbv9bkSwxKTVxtwXQ)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQE5)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5QE5)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, E5DatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, gcd_NyIYzlvRlaYMXjC9bFXqILg)(NI a, NI b) {
	NI result;
	nimfr_("gcd", "E5.nim");
{	result = (NI)0;
	nimln_(4, "E5.nim");
	{
		if (!(b == ((NI) 0))) goto LA3_;
		nimln_(5, "E5.nim");
		result = a;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_v5STcsFPbORM5eGVfZSgyw_2;
		nimln_(7, "E5.nim");
		TM_v5STcsFPbORM5eGVfZSgyw_2 = modInt(a, b);
		result = gcd_NyIYzlvRlaYMXjC9bFXqILg(b, (NI)(TM_v5STcsFPbORM5eGVfZSgyw_2));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, lcm_NyIYzlvRlaYMXjC9bFXqILg_2)(NI a, NI b) {
	NI result;
	NI TM_v5STcsFPbORM5eGVfZSgyw_3;
	NI T1_;
	NI TM_v5STcsFPbORM5eGVfZSgyw_4;
	nimfr_("lcm", "E5.nim");
	result = (NI)0;
	nimln_(10, "E5.nim");
	TM_v5STcsFPbORM5eGVfZSgyw_3 = mulInt(a, b);
	T1_ = (NI)0;
	T1_ = gcd_NyIYzlvRlaYMXjC9bFXqILg(a, b);
	TM_v5STcsFPbORM5eGVfZSgyw_4 = divInt((NI)(TM_v5STcsFPbORM5eGVfZSgyw_3), T1_);
	result = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_4);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, lcm2_U9cX9bzGSpzbFx9aiSoGcVS5g)(tySequence_qwqHTkRvwhrRyENtudHQ7g* A) {
	NI result;
	NI l;
	nimfr_("lcm2", "E5.nim");
{	result = (NI)0;
	nimln_(13, "E5.nim");
	{
		NI T3_;
		T3_ = (A ? A->Sup.len : 0);
		if (!(T3_ == ((NI) 1))) goto LA4_;
		nimln_(14, "E5.nim");
		if ((NU)(((NI) 0)) >= (NU)(A->Sup.len)) raiseIndexError();
		result = A->data[((NI) 0)];
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(15, "E5.nim");
	if ((NU)(((NI) 0)) >= (NU)(A->Sup.len)) raiseIndexError();
	l = A->data[((NI) 0)];
	{
		NI i;
		NI colontmp_;
		NI T7_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(16, "E5.nim");
		T7_ = (A ? (A->Sup.len-1) : -1);
		colontmp_ = T7_;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_v5STcsFPbORM5eGVfZSgyw_5;
				if (!(res <= colontmp_)) goto LA9;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(17, "E5.nim");
				if ((NU)(i) >= (NU)(A->Sup.len)) raiseIndexError();
				l = lcm_NyIYzlvRlaYMXjC9bFXqILg_2(l, A->data[i]);
				nimln_(2048, "system.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_5 = addInt(res, ((NI) 1));
				res = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_5);
			} LA9: ;
		}
	}
	nimln_(18, "E5.nim");
	result = l;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQE5)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NI result;
	NI TM_v5STcsFPbORM5eGVfZSgyw_6;
	NI TM_v5STcsFPbORM5eGVfZSgyw_7;
	nimfr_("len", "system.nim");
	result = (NI)0;
	nimln_(2181, "system.nim");
	TM_v5STcsFPbORM5eGVfZSgyw_6 = subInt(x.b, x.a);
	TM_v5STcsFPbORM5eGVfZSgyw_7 = addInt((NI)(TM_v5STcsFPbORM5eGVfZSgyw_6), ((NI) 1));
	result = ((((NI) 0) >= (NI)(TM_v5STcsFPbORM5eGVfZSgyw_7)) ? ((NI) 0) : (NI)(TM_v5STcsFPbORM5eGVfZSgyw_7));
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5QE5)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_qXw3Fibbv9bkSwxKTVxtwXQ)(void) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* c;
	NI i;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T1_;
	NI T2_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
	NI T7_;
	nimfr_("main", "E5.nim");
	nimln_(20, "E5.nim");
	nimln_(500, "sequtils.nim");
	i = ((NI) 0);
	nimln_(501, "sequtils.nim");
	nimln_(20, "E5.nim");
	T1_ = dotdot__vDQySKWzgnxQdUarow6k5QE5(((NI) 1), ((NI) 20));
	T2_ = (NI)0;
	T2_ = len_dieebyw8huA9adTlIwdsH9bQE5(T1_);
	result = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange(T2_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI x;
		NI res;
		x = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_v5STcsFPbORM5eGVfZSgyw_8;
				NI TM_v5STcsFPbORM5eGVfZSgyw_9;
				if (!(res <= ((NI) 20))) goto LA5;
				nimln_(2047, "system.nim");
				x = res;
				if ((NU)(i) >= (NU)(result->Sup.len)) raiseIndexError();
				nimln_(503, "sequtils.nim");
				result->data[i] = x;
				nimln_(504, "sequtils.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_8 = addInt(i, ((NI) 1));
				i = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_8);
				nimln_(2048, "system.nim");
				TM_v5STcsFPbORM5eGVfZSgyw_9 = addInt(res, ((NI) 1));
				res = (NI)(TM_v5STcsFPbORM5eGVfZSgyw_9);
			} LA5: ;
		}
	}
	genericSeqAssign((&c), result, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	nimln_(21, "E5.nim");
	memset((void*)T6_, 0, sizeof(T6_));
	T7_ = (NI)0;
	T7_ = lcm2_U9cX9bzGSpzbFx9aiSoGcVS5g(c);
	T6_[0] = nimIntToStr(T7_);
	echoBinSafe(T6_, 1);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_futureDatInit000();
	stdlib_mathDatInit000();
	stdlib_sequtilsDatInit000();
	E5DatInit000();
	stdlib_macrosInit000();
	stdlib_futureInit000();
	stdlib_mathInit000();
	stdlib_sequtilsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("E5", "E5.nim");
	nimln_(23, "E5.nim");
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(24, "E5.nim");
		main_qXw3Fibbv9bkSwxKTVxtwXQ();
	}
	LA3_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, E5DatInit000)(void) {
}

