/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -I/usr/share/nim -o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E6.o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E6.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NI, sum1_FGXQvH5u4lgd7k9cY15VE4g)(void);
N_LIB_PRIVATE N_NIMCALL(NI, roof__quCe21GD6ES9cmTsTs9cYP7Q)(NI x, NI y);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, sum2_FGXQvH5u4lgd7k9cY15VE4g_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, main_sDMuk1GKMYVozgyirQyCTg)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, E6DatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, sum1_FGXQvH5u4lgd7k9cY15VE4g)(void) {
	NI result;
	NI a;
	nimfr_("sum_1", "E6.nim");
{	result = (NI)0;
	nimln_(4, "E6.nim");
	a = ((NI) 0);
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI T4_;
				NI TM_RDDCG5jkaSKvwg2aya9cI2g_2;
				NI TM_RDDCG5jkaSKvwg2aya9cI2g_3;
				if (!(res <= ((NI) 100))) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(6, "E6.nim");
				T4_ = (NI)0;
				T4_ = roof__quCe21GD6ES9cmTsTs9cYP7Q(i, ((NI) 2));
				TM_RDDCG5jkaSKvwg2aya9cI2g_2 = addInt(a, T4_);
				a = (NI)(TM_RDDCG5jkaSKvwg2aya9cI2g_2);
				nimln_(2048, "system.nim");
				TM_RDDCG5jkaSKvwg2aya9cI2g_3 = addInt(res, ((NI) 1));
				res = (NI)(TM_RDDCG5jkaSKvwg2aya9cI2g_3);
			} LA3: ;
		}
	}
	nimln_(7, "E6.nim");
	result = a;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, sum2_FGXQvH5u4lgd7k9cY15VE4g_2)(void) {
	NI result;
	NI b;
	nimfr_("sum_2", "E6.nim");
{	result = (NI)0;
	nimln_(10, "E6.nim");
	b = ((NI) 0);
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_RDDCG5jkaSKvwg2aya9cI2g_4;
				NI TM_RDDCG5jkaSKvwg2aya9cI2g_5;
				if (!(res <= ((NI) 100))) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(12, "E6.nim");
				TM_RDDCG5jkaSKvwg2aya9cI2g_4 = addInt(b, i);
				b = (NI)(TM_RDDCG5jkaSKvwg2aya9cI2g_4);
				nimln_(2048, "system.nim");
				TM_RDDCG5jkaSKvwg2aya9cI2g_5 = addInt(res, ((NI) 1));
				res = (NI)(TM_RDDCG5jkaSKvwg2aya9cI2g_5);
			} LA3: ;
		}
	}
	nimln_(13, "E6.nim");
	result = roof__quCe21GD6ES9cmTsTs9cYP7Q(b, ((NI) 2));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_sDMuk1GKMYVozgyirQyCTg)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NI T2_;
	NI T3_;
	NI TM_RDDCG5jkaSKvwg2aya9cI2g_6;
	nimfr_("main", "E6.nim");
	nimln_(16, "E6.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NI)0;
	T2_ = sum2_FGXQvH5u4lgd7k9cY15VE4g_2();
	T3_ = (NI)0;
	T3_ = sum1_FGXQvH5u4lgd7k9cY15VE4g();
	TM_RDDCG5jkaSKvwg2aya9cI2g_6 = subInt(T2_, T3_);
	T1_[0] = nimIntToStr((NI)(TM_RDDCG5jkaSKvwg2aya9cI2g_6));
	echoBinSafe(T1_, 1);
	popFrame();
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y) {
	NI TM_RDDCG5jkaSKvwg2aya9cI2g_7;
	nimfr_("*=", "system.nim");
	nimln_(3695, "system.nim");
	TM_RDDCG5jkaSKvwg2aya9cI2g_7 = mulInt((*x), y);
	(*x) = (NI)(TM_RDDCG5jkaSKvwg2aya9cI2g_7);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	E6DatInit000();
	stdlib_mathInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("E6", "E6.nim");
	nimln_(18, "E6.nim");
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(19, "E6.nim");
		main_sDMuk1GKMYVozgyirQyCTg();
	}
	LA3_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, E6DatInit000)(void) {
}

