/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -I/usr/share/nim -o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E9.o /home/sangho/Documents/Euler/NIM_Euler/nim.Euler/nimcache/E9.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NI, tri_Z4XqItTQCO1Mu3utjgxmtg)(void);
N_LIB_PRIVATE N_NIMCALL(NI, roof__quCe21GD6ES9cmTsTs9cYP7Q)(NI x, NI y);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, E9DatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, tri_Z4XqItTQCO1Mu3utjgxmtg)(void) {
	NI result;
	nimfr_("tri", "E9.nim");
	result = (NI)0;
	{
		NI b;
		NI res;
		b = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_10;
				if (!(res <= ((NI) 1000))) goto LA3;
				nimln_(2047, "system.nim");
				b = res;
				{
					NI a;
					NI res_2;
					a = (NI)0;
					nimln_(2045, "system.nim");
					res_2 = b;
					{
						nimln_(2046, "system.nim");
						while (1) {
							NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_9;
							if (!(res_2 <= ((NI) 1000))) goto LA6;
							nimln_(2047, "system.nim");
							a = res_2;
							nimln_(6, "E9.nim");
							{
								NI T9_;
								NI T10_;
								NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_2;
								NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_3;
								NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_4;
								NI T11_;
								tyArray_nHXaesL0DJZHyVS07ARPRA T14_;
								NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_5;
								NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_6;
								NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_7;
								NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_8;
								T9_ = (NI)0;
								T9_ = roof__quCe21GD6ES9cmTsTs9cYP7Q(a, ((NI) 2));
								T10_ = (NI)0;
								T10_ = roof__quCe21GD6ES9cmTsTs9cYP7Q(b, ((NI) 2));
								TM_rUiZ9c9cRQFDbJVkciX09a7Ag_2 = addInt(T9_, T10_);
								TM_rUiZ9c9cRQFDbJVkciX09a7Ag_3 = subInt(((NI) 1000), a);
								TM_rUiZ9c9cRQFDbJVkciX09a7Ag_4 = subInt((NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_3), b);
								T11_ = (NI)0;
								T11_ = roof__quCe21GD6ES9cmTsTs9cYP7Q((NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_4), ((NI) 2));
								if (!((NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_2) == T11_)) goto LA12_;
								nimln_(7, "E9.nim");
								memset((void*)T14_, 0, sizeof(T14_));
								TM_rUiZ9c9cRQFDbJVkciX09a7Ag_5 = subInt(((NI) 1000), a);
								TM_rUiZ9c9cRQFDbJVkciX09a7Ag_6 = subInt((NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_5), b);
								TM_rUiZ9c9cRQFDbJVkciX09a7Ag_7 = mulInt((NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_6), a);
								TM_rUiZ9c9cRQFDbJVkciX09a7Ag_8 = mulInt((NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_7), b);
								T14_[0] = nimIntToStr((NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_8));
								echoBinSafe(T14_, 1);
							}
							LA12_: ;
							nimln_(2048, "system.nim");
							TM_rUiZ9c9cRQFDbJVkciX09a7Ag_9 = addInt(res_2, ((NI) 1));
							res_2 = (NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_9);
						} LA6: ;
					}
				}
				TM_rUiZ9c9cRQFDbJVkciX09a7Ag_10 = addInt(res, ((NI) 1));
				res = (NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_10);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y) {
	NI TM_rUiZ9c9cRQFDbJVkciX09a7Ag_11;
	nimfr_("*=", "system.nim");
	nimln_(3695, "system.nim");
	TM_rUiZ9c9cRQFDbJVkciX09a7Ag_11 = mulInt((*x), y);
	(*x) = (NI)(TM_rUiZ9c9cRQFDbJVkciX09a7Ag_11);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	E9DatInit000();
	stdlib_mathInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NI T2_;
	nimfr_("E9", "E9.nim");
	nimln_(9, "E9.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NI)0;
	T2_ = tri_Z4XqItTQCO1Mu3utjgxmtg();
	T1_[0] = nimIntToStr(T2_);
	echoBinSafe(T1_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, E9DatInit000)(void) {
}

